### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HMStitt**
marked it as unmaintained

### CODE REVIEW

**Comment by knowtheory** [comment]
Let's do it one better, and i'll archive it as well!

**Comment by knowtheory** [comment]
Oh whoops, this one is on your repo :)

**Comment by nathanstitt** [comment]
hehe!  Holly's participating in hacktoberfest this year and hunting for documentation PRs.   good idea to archive though, i'll probably do so next month after her continuation is counted

**Comment by knowtheory** [comment]
Nice!  Hope you're having a good time and doing well!

**Pull request merged**
